spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/langme_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

